### ISSUE TITLE
service deregister bug

### ISSUE THREAD

**Issue by wanghuatao** [rickfast/consul-client#281] opened 2017-12-05 12:37 UTC
if i use agentClient.deregister() ,the http method   @PUT("agent/service/deregister/{serviceId}") will changed to get 

Response{protocol=http/1.1, code=405, message=Method Not Allowed, url=http://127.0.0.1:8500/v1/agent/service/deregister/sId:akka.tcp:/ClusterSystem@127.0.1.1:37390?consistent=}

**Comment by yfouquet** [comment] 2018-08-18 20:06
The issue is due to the "/" in your service id that leads the Consul agent in error.
The issue is known by hashicorp. See issue https://github.com/hashicorp/consul/issues/2813 entitled "Consul issues 301 response to deregister requests with / in the service ID".

**Comment by yfouquet** [comment] 2018-08-18 20:08
Closing the issue as '/' in the service ID is valid; the Consul agent is to be fixed.

**Closed by yfouquet** 2018-08-18 20:08 UTC
